server:
  port: 8001
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
############################################################
#
# 设置域名
#
############################################################
website:
  domain-name: imoocnews.com

############################################################
#
# 在 dev 环境下，开启 MyBatis 的日志打印
#
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
