server:
  port: 8105
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
############################################################
#
# 设置域名
#
############################################################
website:
  domain-name: imoocnews.com