############################################################
#
# 文件微服务
# web访问端口号  开发环境中约定：8004；生产环境中约定：8104；测试环境中约定：8204
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev # 环境配置：dev 为开发环境；test 为测试环境；prod 为生产环境
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000 # 限制一次请求单个文件大小，最大为 500 KB
      max-request-size: 512000 # 限制一次请求多个文件大小，最大为 500 KB
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: imooc-news